/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, OurTeam as PrismaOurTeam } from "@prisma/client";

export class OurTeamServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.OurTeamCountArgs, "select">): Promise<number> {
    return this.prisma.ourTeam.count(args);
  }

  async ourTeams(args: Prisma.OurTeamFindManyArgs): Promise<PrismaOurTeam[]> {
    return this.prisma.ourTeam.findMany(args);
  }
  async ourTeam(
    args: Prisma.OurTeamFindUniqueArgs
  ): Promise<PrismaOurTeam | null> {
    return this.prisma.ourTeam.findUnique(args);
  }
  async createOurTeam(args: Prisma.OurTeamCreateArgs): Promise<PrismaOurTeam> {
    return this.prisma.ourTeam.create(args);
  }
  async updateOurTeam(args: Prisma.OurTeamUpdateArgs): Promise<PrismaOurTeam> {
    return this.prisma.ourTeam.update(args);
  }
  async deleteOurTeam(args: Prisma.OurTeamDeleteArgs): Promise<PrismaOurTeam> {
    return this.prisma.ourTeam.delete(args);
  }
}
