/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request, Response } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FileInterceptor } from "@nestjs/platform-express";
import { HeroSliderService } from "../heroSlider.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HeroSliderCreateInput } from "./HeroSliderCreateInput";
import { HeroSlider } from "./HeroSlider";
import { HeroSliderFindManyArgs } from "./HeroSliderFindManyArgs";
import { HeroSliderWhereUniqueInput } from "./HeroSliderWhereUniqueInput";
import { HeroSliderUpdateInput } from "./HeroSliderUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HeroSliderControllerBase {
  constructor(
    protected readonly service: HeroSliderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HeroSlider })
  @nestAccessControl.UseRoles({
    resource: "HeroSlider",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHeroSlider(
    @common.Body() data: HeroSliderCreateInput
  ): Promise<HeroSlider> {
    return await this.service.createHeroSlider({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        heading: true,
        buttonText: true,
        buttonLink: true,
        image: true,
        subHeading: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HeroSlider] })
  @ApiNestedQuery(HeroSliderFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HeroSlider",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async heroSliders(@common.Req() request: Request): Promise<HeroSlider[]> {
    const args = plainToClass(HeroSliderFindManyArgs, request.query);
    return this.service.heroSliders({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        heading: true,
        buttonText: true,
        buttonLink: true,
        image: true,
        subHeading: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HeroSlider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HeroSlider",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async heroSlider(
    @common.Param() params: HeroSliderWhereUniqueInput
  ): Promise<HeroSlider | null> {
    const result = await this.service.heroSlider({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        heading: true,
        buttonText: true,
        buttonLink: true,
        image: true,
        subHeading: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HeroSlider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HeroSlider",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHeroSlider(
    @common.Param() params: HeroSliderWhereUniqueInput,
    @common.Body() data: HeroSliderUpdateInput
  ): Promise<HeroSlider | null> {
    try {
      return await this.service.updateHeroSlider({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          heading: true,
          buttonText: true,
          buttonLink: true,
          image: true,
          subHeading: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HeroSlider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HeroSlider",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHeroSlider(
    @common.Param() params: HeroSliderWhereUniqueInput
  ): Promise<HeroSlider | null> {
    try {
      return await this.service.deleteHeroSlider({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          heading: true,
          buttonText: true,
          buttonLink: true,
          image: true,
          subHeading: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Put(":id/image")
  @common.UseInterceptors(FileInterceptor("file"))
  @swagger.ApiConsumes("multipart/form-data")
  @swagger.ApiBody({
    schema: {
      type: "object",

      properties: {
        file: {
          type: "string",
          format: "binary",
        },
      },
    },
  })
  @swagger.ApiParam({
    name: "id",
    type: "string",
    required: true,
  })
  @swagger.ApiCreatedResponse({
    type: HeroSlider,
    status: "2XX",
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async uploadImage(
    @common.Param()
    params: HeroSliderWhereUniqueInput,
    @common.UploadedFile()
    file: Express.Multer.File
  ): Promise<HeroSlider> {
    return this.service.uploadImage(
      {
        where: params,
      },
      Object.assign(file, {
        filename: file.originalname,
      })
    );
  }

  @common.Get(":id/image")
  @swagger.ApiParam({
    name: "id",
    type: "string",
    required: true,
  })
  @swagger.ApiOkResponse({
    type: common.StreamableFile,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async downloadImage(
    @common.Param()
    params: HeroSliderWhereUniqueInput,
    @common.Res({
      passthrough: true,
    })
    res: Response
  ): Promise<common.StreamableFile> {
    const result = await this.service.downloadImage({
      where: params,
    });

    if (result === null) {
      throw new errors.NotFoundException(
        "No resource was found for ",
        JSON.stringify(params)
      );
    }

    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${result.filename}`
    );
    res.setHeader("Content-Type", result.mimetype);
    return result.stream;
  }

  @common.Delete(":id/image")
  @swagger.ApiOkResponse({
    type: HeroSlider,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async deleteImage(
    @common.Param()
    params: HeroSliderWhereUniqueInput
  ): Promise<HeroSlider> {
    return this.service.deleteImage({
      where: params,
    });
  }
}
